[build]
  command = "source /opt/buildhome/pythonpython-3.8/bin/activate && python Cathy.py"
  publish = "/dev/null"
  
[[plugins]]
  package = "netlify-plugin-cache"
  
[build.environment]
  PIP_UPGRADE = "1"
  
[build.environment.variables]
  PATH = "/opt/buildhome/pythonpython-3.8/bin:/opt/buildhome/pythonpython3.8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[install]
  command = """
    pip install --upgrade pip
    pip install -r requirements.txt
  """
